import "./IdCss.css";

export function IdCss(){
    return(
        <>
            <h1 id="main">Creating a site with HTML and CSS</h1>
            <h1>Learning HTML</h1>
            <h2 className="basic">Basic</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima veniam doloremque tempora fugit doloribus deleniti. Ipsa distinctio excepturi aspernatur quasi reiciendis ipsam delectus corporis cupiditate maxime similique, voluptatibus voluptatem libero. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui, nemo eos? Explicabo cupiditate dicta reiciendis quas ipsam iure esse autem maxime. Laudantium omnis at labore impedit quisquam numquam excepturi soluta.</p>
            <h2 className="intermediate">Intermediate</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima veniam doloremque tempora fugit doloribus deleniti. Ipsa distinctio excepturi aspernatur quasi reiciendis ipsam delectus corporis cupiditate maxime similique, voluptatibus voluptatem libero. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui, nemo eos? Explicabo cupiditate dicta reiciendis quas ipsam iure esse autem maxime. Laudantium omnis at labore impedit quisquam numquam excepturi soluta.</p>
            <h2 className="advanced">Advanced</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima veniam doloremque tempora fugit doloribus deleniti. Ipsa distinctio excepturi aspernatur quasi reiciendis ipsam delectus corporis cupiditate maxime similique, voluptatibus voluptatem libero. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui, nemo eos? Explicabo cupiditate dicta reiciendis quas ipsam iure esse autem maxime. Laudantium omnis at labore impedit quisquam numquam excepturi soluta.</p>
            <h1>Learning CSS</h1>
            <h2 className="basic">Basic</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error reprehenderit dignissimos, delectus nostrum aut assumenda a dolorem explicabo repellat suscipit atque consequuntur libero harum cupiditate expedita velit ducimus laudantium at? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem atque obcaecati nemo similique aliquam, cum magnam, repellat ad voluptate, iste nam commodi placeat quae non odio illum labore corporis odit! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis odit molestias at obcaecati quis doloremque illo distinctio dolorem, laudantium a provident optio, repellat numquam temporibus! Illum id aliquid libero enim.</p>
            <h2 className="intermediate">Intermediate</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error reprehenderit dignissimos, delectus nostrum aut assumenda a dolorem explicabo repellat suscipit atque consequuntur libero harum cupiditate expedita velit ducimus laudantium at? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem atque obcaecati nemo similique aliquam, cum magnam, repellat ad voluptate, iste nam commodi placeat quae non odio illum labore corporis odit! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis odit molestias at obcaecati quis doloremque illo distinctio dolorem, laudantium a provident optio, repellat numquam temporibus! Illum id aliquid libero enim.</p>
            <h2 className="advanced">Advanced</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error reprehenderit dignissimos, delectus nostrum aut assumenda a dolorem explicabo repellat suscipit atque consequuntur libero harum cupiditate expedita velit ducimus laudantium at? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem atque obcaecati nemo similique aliquam, cum magnam, repellat ad voluptate, iste nam commodi placeat quae non odio illum labore corporis odit! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis odit molestias at obcaecati quis doloremque illo distinctio dolorem, laudantium a provident optio, repellat numquam temporibus! Illum id aliquid libero enim.</p>
            <h1>Learning TS</h1>
            <h2 className="basic">Basic</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error reprehenderit dignissimos, delectus nostrum aut assumenda a dolorem explicabo repellat suscipit atque consequuntur libero harum cupiditate expedita velit ducimus laudantium at? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem atque obcaecati nemo similique aliquam, cum magnam, repellat ad voluptate, iste nam commodi placeat quae non odio illum labore corporis odit! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis odit molestias at obcaecati quis doloremque illo distinctio dolorem, laudantium a provident optio, repellat numquam temporibus! Illum id aliquid libero enim.</p>
            <h2 className="intermediate">Intermediate</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error reprehenderit dignissimos, delectus nostrum aut assumenda a dolorem explicabo repellat suscipit atque consequuntur libero harum cupiditate expedita velit ducimus laudantium at? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem atque obcaecati nemo similique aliquam, cum magnam, repellat ad voluptate, iste nam commodi placeat quae non odio illum labore corporis odit! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis odit molestias at obcaecati quis doloremque illo distinctio dolorem, laudantium a provident optio, repellat numquam temporibus! Illum id aliquid libero enim.</p>
            <h2 className="advanced important">Advanced</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error reprehenderit dignissimos, delectus nostrum aut assumenda a dolorem explicabo repellat suscipit atque consequuntur libero harum cupiditate expedita velit ducimus laudantium at? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Rem atque obcaecati nemo similique aliquam, cum magnam, repellat ad voluptate, iste nam commodi placeat quae non odio illum labore corporis odit! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Debitis odit molestias at obcaecati quis doloremque illo distinctio dolorem, laudantium a provident optio, repellat numquam temporibus! Illum id aliquid libero enim.</p>
        </>
    );
}
